apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: groovyPrintLoopTask
spec:
  selector:
    matchLabels:
      app: groovyPrintLoopTask
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: groovyPrintLoopTask
      labels:
        app: groovyPrintLoopTask
    spec:
      containers:
      - name: groovyPrintLoopTask
        image: 172.30.177.25:5000/groovy/ose-groovy-tasks:latest
        command: ["gradle",  "loopPrintln", "-p", "/opt/app-root/src/source/"]
      restartPolicy: Never